$LOAD_PATH.unshift File.expand_path('../../../lib', __FILE__)
require 'emfrp'
require 'stringio'

FILES = Dir.glob("./*.mfrp")

task :default do
  FILES.each do |f|
    puts "TESTING #{f}".colorize(:light_blue)
    expected_code = File.open(f, 'r'){|f| f.gets[1..-1].chomp.strip.to_sym}
    begin
      out = StringIO.new
      inter = Emfrp::Interpreter.new(Emfrp::IncludeDirs, out, f)
      puts " => fail".colorize(:red)
    rescue Emfrp::Interpreter::InterpreterError => err
      if err.code == expected_code
        puts " => ok".colorize(:green)
      else
        puts "Error code `#{expected_code}' is expected, but actual is `#{err.code}'."
        out.string.each_line do |line|
          print ">> " + line
        end
        puts " => fail".colorize(:red)
      end
    end
  end
end
